def print_hi(name):
    # Используйте точку останова в строке кода ниже для отладки скрипта.
    print(f'Hi, {name}')  # Нажмите Ctrl+F8 для переключения точки останова.
    # print(f'Hi, {name}') 


